---
title: "JN_Bio720_R_InClass_Contol_flow_worked_example"
author: "Jalees Nasir"
date: "October 29, 2018"
output: html_document
---

# Introduction
Let's do a little exercise integrating some of the things we have learned. Here are some Illumina HiSeq reads for one of our recent projects:

```{r}
read_1 <- "CGCGCAGTAGGGCACATGCCAGGTGTCCGCCACTTGGTGGGCACACAGCCGATGACGAACGGGCTCCTTGACTATAATCTGACCCGTTTGCGTTTGGGTGACCAGGGAGAACTGGTGCTCCTGC"
read_2 <- "AAAAAGCCAACCGAGAAATCCGCCAAGCCTGGCGACAAGAAGCCAGAGCAGAAGAAGACTGCTGCGGCTCCCGCTGCCGGCAAGAAGGAGGCTGCTCCCTCGGCTGCCAAGCCAGCTGCCGCTG"
read_3  <- "CAGCACGGACTGGGGCTTCTTGCCGGCGAGGACCTTCTTCTTGGCATCCTTGCTCTTGGCCTTGGCGGCCGCGGTCGTCTTTACGGCCGCGGGCTTCTTGGCAGCAGCACCGGCGGTCGCTGGC"
```

**Question 1. what species are these sequences from?**

The sequences seem to be from *Drosophila melanogaster*.

**Question 2. Put all three of these reads into a single object (a vector).  What class will the vector `reads` be? Check to make sure! How many characters are in each read (and why does `length()` not give you what you want.. try...)**

The class of the resulting vector should be "character".
length() doesn't give what we expecT because the length of the vector are the number of elements (which are 3).

The number of characters in each element is 124 (nchar).

```{R}
reads <- c(read_1, read_2, read_3)
class(reads)
nchar(reads)

length(reads)

```

**Question 3. Say we wanted to print each character (not the full string) from read_1, how do we do this using a for loop? You may wish to look at a function like `strsplit()` to accomplish this (there are other ways.)**

Replace the blanks.
```{R}
read_1_split <- strsplit(read_1, split = "", fixed = T) 

for (i in read_1_split){
  print(i)
}
```

**Question 4. What kind of object does this return? How might we make it a character vector again?**

It returns a list.
```{R}
class(read_1_split)
```
We would convert it back to a character vector via "as.character" after unlisting it.

```{R}
read_1_char <- as.character(unlist(read_1_split))
class(read_1_char)
```


**Question 5. How about if we wanted the number of occurrences of each base? Or better yet, their frequencies? You could write a loop, but I suggest looking at the help for the `table()` function... Also keep in mind that for for most objects `length()` tells you how many elements there are in a vector. For lists use `lengths()` (so you can either do this on a character vector or a list, your choice)**

```{R}
freq <- table(read_1_split)/lengths(read_1_split)
print(freq)
```

**Question 6. How would you make this into a nice looking function that can work on either  a list or vectors of characters? (Still just for a single read)**

```{R}
BFreq <- function(x){
  if (mode(x) == "list"){
    table <- table(x)/lengths(x)
  } else {
    table <- table(x)/length(x)
  }
  return(table)
}

BFreq(read_1_split)
```

**Question 7. Now how can you modify your approach to do it for an arbitrary numbers of reads? You could use a loop or use one of the apply like functions (which one)?**

```{R}
BFreq <- function(x){
  if (mode(x) == "list"){
    table <- table(x)/lengths(x)
  } else {
    table <- table(x)/length(x)
  }
  return(table)
}
reads <- c(read_1_split, read_2_split <- strsplit(read_2, split = "", fixed = T), read_3_split <- strsplit(read_3, split = "", fixed = T))

sapply(reads, BFreq)
```

**Question 8. Can you revise your function so that it can handle the input of either a string as a single multicharacter vector, **or** a vector of individual characters **or** a list? Try it out with the vector of three sequence reads (`reads`).**

```{R}
BFreq <- function(x) {
    
    if (length(x) == 1 & mode(x) == "character") {
      x <- strsplit(x, split = "", fixed = T) 
      x <- as.character(unlist(x))
    } 
  if (mode(x) == "list") {
    	table <- table(x)/lengths(x)
    	} else {
    	table <- table(x)/length(x)
    	}
  return(table)
  }
   
```


```{R}
basefreq <- sapply(reads, BFreq, USE.NAMES = F)
print(basefreq)
```